In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression, Ridge

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

csv_file = '/content/drive/My Drive/TFG_AlienEmbarecRiadi/hotel_bookings_modified.csv'
df = pd.read_csv(csv_file, delimiter=',')

df.to_csv("/content/drive/My Drive/TFG_AlienEmbarecRiadi/hotel_bookings_str.csv", index=False)

print(df.head(10))

df.isna().sum()
# df.to_csv("/content/drive/My Drive/TFG_AlienEmbarecRiadi/hotel_bookings_modified.csv", index=False)

          hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  adults  children  babies meal country market_segment distribution_channel  is_repeated_guest  previous_cancellations  previous_bookings_not_canceled reserved_room_type assigned_room_type  booking_changes deposit_type  agent  days_in_waiting_list customer_type    adr  required_car_parking_spaces  total_of_special_requests reservation_status reservation_status_date  total_stayed_nights  weekend_nights_proportion  arrival_year_week
0  Resort Hotel            0        342               2015               July                        27                          1                        0                     0       2         0       0   BB     PRT         Direct               Direct                  0                       0                               0                  C                  C                3   No 

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              0
babies                                0
meal                                  0
country                               0
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             16340
days_in_waiting_list                  0


In [ ]:
data["reservation_status_date"] = pd.to_datetime(data["reservation_status_date"]).dt.strftime("%Y%m%d")
print(data['reservation_status_date'])


0         20150701
1         20150701
2         20150702
3         20150702
4         20150703
            ...   
119385    20170906
119386    20170907
119387    20170907
119388    20170907
119389    20170907
Name: reservation_status_date, Length: 119390, dtype: object


In [ ]:
data['meal'].unique()
valores_meal = {'meal':{'SC':0,'BB':1,'HB':2,'FB':3}}
data.replace(valores_meal, inplace=True)
print(data['meal'])

0         1
1         1
2         1
3         1
4         1
         ..
119385    1
119386    1
119387    1
119388    1
119389    2
Name: meal, Length: 119390, dtype: int64


In [ ]:
data['hotel'].unique()
valores_hotel = {'hotel':{'Resort Hotel': 1, 'City Hotel': 0}}
data.replace(valores_hotel, inplace=True)
print(data['hotel'])

0         1
1         1
2         1
3         1
4         1
         ..
119385    0
119386    0
119387    0
119388    0
119389    0
Name: hotel, Length: 119390, dtype: int64


In [ ]:
data['arrival_date_month'].unique()
valores_arrival_month = {'arrival_date_month':{'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6, 'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12}}
data.replace(valores_arrival_month, inplace=True)
print(data['arrival_date_month'])

0         7
1         7
2         7
3         7
4         7
         ..
119385    8
119386    8
119387    8
119388    8
119389    8
Name: arrival_date_month, Length: 119390, dtype: int64


In [ ]:
del data['country']

In [ ]:
cols = data.columns[data.dtypes.eq('object')]
cols

Index(['market_segment', 'distribution_channel', 'reserved_room_type', 'assigned_room_type', 'deposit_type', 'customer_type', 'reservation_status', 'reservation_status_date'], dtype='object')

In [ ]:
data['market_segment'].unique()
valores_market_segment = {'market_segment': {'Direct': 0, 'Corporate': 1, 'Online TA': 2, 'Offline TA/TO': 3, 'Complementary': 5, 'Groups': 6, 'Unknown': 7, 'Aviation': 8}}
data.replace(valores_market_segment, inplace=True)


In [ ]:
data['distribution_channel'].unique()
valores_distribution_channel = {'distribution_channel': {'Direct': 0, 'Corporate': 1, 'TA/TO': 2, 'Unknown': 3, 'GDS': 4}}
data.replace(valores_distribution_channel, inplace=True)

array([0, 1, 2, 3, 4])

In [ ]:
data['reserved_room_type'].unique()

array(['C', 'A', 'D', 'E', 'G', 'F', 'H', 'L', 'P', 'B'], dtype=object)

In [ ]:
valores_reserved_room_type = {'reserved_room_type': {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'L': 8, 'P': 9}}
data.replace(valores_reserved_room_type, inplace=True)


TypeError: ignored

In [ ]:
data['reserved_room_type'].unique()

array([2, 0, 3, 4, 6, 5, 7, 8, 9, 1])

In [ ]:
data['reserved_room_type'].unique()

array([2, 0, 3, 4, 6, 5, 7, 8, 9, 1])

In [ ]:
valores_reserved_room_type = {'assigned_room_type': {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'L': 8, 'P': 9, 'I': 10, 'K': 11,}}
data.replace(valores_reserved_room_type, inplace=True)
data['assigned_room_type'].unique()

array([ 2,  0,  3,  4,  6,  5, 10,  1,  7,  9,  8, 11])

In [ ]:
data['deposit_type'].unique()

array(['No Deposit', 'Refundable', 'Non Refund'], dtype=object)

In [ ]:
valores_deposit_type = {'deposit_type': {'No Deposit': 0, 'Refundable': 1, 'Non Refund': 2}}
data.replace(valores_deposit_type, inplace=True)

In [ ]:
data['deposit_type'].unique()

array([0, 1, 2])

In [ ]:
data['customer_type'].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [ ]:
valores_customer_type = {'customer_type': {'Transient': 0, 'Contract': 1, 'Transient-Party': 2, 'Group': 3}}
data.replace(valores_customer_type, inplace=True)

In [ ]:
data['customer_type'].unique()

array([0, 1, 2, 3])

In [ ]:
data['reservation_status'].unique()

array(['Check-Out', 'Canceled', 'No-Show'], dtype=object)

In [ ]:
valores_reservation_status = {'reservation_status': {'Check-Out': 0, 'Canceled': 1, 'No-Show': 2}}
data.replace(valores_reservation_status, inplace=True)

In [ ]:
data['reservation_status'].unique()

array([0, 1, 2])

In [ ]:
data['reservation_status_date'] = pd.to_numeric(data.reservation_status_date.str.replace('-',''))

In [ ]:
data['reservation_status_date'].unique()

array([20150701, 20150702, 20150703, 20150506, 20150422, 20150623,
       20150705, 20150706, 20150707, 20150708, 20150511, 20150715,
       20150716, 20150529, 20150519, 20150619, 20150523, 20150518,
       20150709, 20150602, 20150713, 20150704, 20150629, 20150616,
       20150618, 20150612, 20150609, 20150526, 20150711, 20150712,
       20150717, 20150415, 20150513, 20150710, 20150520, 20150512,
       20150714, 20150617, 20150501, 20150330, 20150719, 20150603,
       20150626, 20150514, 20150720, 20150507, 20150528, 20150413,
       20150325, 20150721, 20150627, 20150718, 20150723, 20150608,
       20150622, 20150624, 20150305, 20150601, 20150424, 20150722,
       20150527, 20150406, 20150411, 20150725, 20150728, 20150729,
       20150625, 20150724, 20150605, 20150630, 20150613, 20150611,
       20150730, 20150727, 20150429, 20150604, 20150726, 20150801,
       20150802, 20150615, 20150423, 20150731, 20150525, 20150803,
       20150417, 20150804, 20150806, 20150515, 20150509, 20150

In [ ]:
data['reservation_status_date']

0         20150701
1         20150701
2         20150702
3         20150702
4         20150703
            ...   
119385    20170906
119386    20170907
119387    20170907
119388    20170907
119389    20170907
Name: reservation_status_date, Length: 119390, dtype: int64

In [ ]:
cols = data.columns[data.dtypes.eq('object')]
cols


Index([], dtype='object')

In [ ]:
datos_pred = data[['lead_time', 'adr', 'arrival_date_month', 'total_stayed_nights','stays_in_weekend_nights', 'reserved_room_type']].copy()
print(dato_pred)

        lead_time     adr  arrival_date_month  total_stayed_nights  stays_in_weekend_nights  reserved_room_type
0             342    0.00                   7                    0                        0                   2
1             737    0.00                   7                    0                        0                   2
2               7   75.00                   7                    1                        0                   0
3              13   75.00                   7                    1                        0                   0
4              14   98.00                   7                    2                        0                   0
...           ...     ...                 ...                  ...                      ...                 ...
119385         23   96.14                   8                    7                        2                   0
119386        102  225.43                   8                    7                        2             

In [ ]:
datos_entrenamiento = datos_pred.sample(frac=0.8, random_state=0)
datos_test = datos_pred.drop(datos_entrenamiento.index)

In [ ]:
datos_entrenamiento

lead_time     adr  arrival_date_month  total_stayed_nights  stays_in_weekend_nights  reserved_room_type
5627          354   37.56                   5                    7                        2                   0
119322        142   86.10                   8                    3                        0                   0
75310         304   62.00                   8                    2                        1                   0
90032           5  133.10                   5                    4                        2                   3
75368         313   62.00                   8                    2                        0                   0
...           ...     ...                 ...                  ...                      ...                 ...
7772           57  189.00                   8                    2                        0                   0
100386         31  149.00                  10                    3                        0                   0
95066         111  107.10                   8                    2                        0                   0
66008         308  109.80                   4                    8                        2                   0
53253         350  130.00                   6                    2                        0                   0

[95512 rows x 6 columns]

In [ ]:
etiquetas_entrenamiento = datos_entrenamiento.pop('adr')
etiquetas_test = datos_test.pop('adr')

In [ ]:
datos_entrenamiento

lead_time  arrival_date_month  total_stayed_nights  stays_in_weekend_nights  reserved_room_type
5627          354                   5                    7                        2                   0
119322        142                   8                    3                        0                   0
75310         304                   8                    2                        1                   0
90032           5                   5                    4                        2                   3
75368         313                   8                    2                        0                   0
...           ...                 ...                  ...                      ...                 ...
7772           57                   8                    2                        0                   0
100386         31                  10                    3                        0                   0
95066         111                   8                    2                        0                   0
66008         308                   4                    8                        2                   0
53253         350                   6                    2                        0                   0

[95512 rows x 5 columns]

In [ ]:
etiquetas_entrenamiento

5627       37.56
119322     86.10
75310      62.00
90032     133.10
75368      62.00
           ...  
7772      189.00
100386    149.00
95066     107.10
66008     109.80
53253     130.00
Name: adr, Length: 95512, dtype: float64

In [ ]:
etiquetas_test

2          75.00
10        123.00
13        154.77
20         97.29
21         84.67
           ...  
119357     91.02
119361     95.85
119362    119.17
119365    266.75
119386    225.43
Name: adr, Length: 23878, dtype: float64

In [ ]:
cols = data.columns[data.dtypes.eq('object')]
cols

Index([], dtype='object')

In [ ]:
data['agent'].fillna(0, inplace=True)

In [ ]:
from sklearn.linear_model import LinearRegression
modelo = LinearRegression()
modelo.fit(datos_entrenamiento, etiquetas_entrenamiento)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

predicciones = modelo.predict(datos_test)
print(predicciones)

[ 92.72633805 139.59153087 162.88580089 ...  91.45842598 162.52912654
 138.99614776]


In [ ]:

etiquetas_test = etiquetas_test.reshape(-1,1)
predicciones = predicciones.reshape(-1,1)
modelo.score(etiquetas_test, predicciones)

AttributeError: ignored

In [ ]:
import numpy as np
from sklearn.metrics import mean_squared_error
error = np.sqrt(mean_squared_error(etiquetas_test, predicciones))
print("Error porcentual : %f" % (error*100))

Error porcentual : 4385.785685
